<?xml version="1.0" encoding="utf-8"?><Database Name="TutorialDB" Class="DataClasses2DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ольга-пк;Initial Catalog=TutorialDB;Integrated Security=True" SettingsObjectName="TestTask.Properties.Settings" SettingsPropertyName="TutorialDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.skills" Member="skills">
    <Type Name="skills">
      <Column Name="skill_id" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="skill_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>