<?xml version="1.0" encoding="utf-8"?><Database Name="TutorialDB" Class="DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ольга-пк;Initial Catalog=TutorialDB;Integrated Security=True" SettingsObjectName="TestTask.Properties.Settings" SettingsPropertyName="TutorialDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.employees" Member="employees">
    <Type Name="employees">
      <Column Name="employee_id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[first name]" Member="first_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[second name]" Member="second_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="position" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[education]" Member="education" Storage="_education_level" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[date of birth]" Member="date_of_birth" Storage="_year_of_birth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[passport number]" Member="passport_number" Storage="_pasport_number" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="[phone number]" Member="phone_number" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="mail" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="employees_ps" Member="ps" ThisKey="employee_id" OtherKey="person_id" Type="ps" />
    </Type>
  </Table>
  <Table Name="dbo.ps" Member="ps">
    <Type Name="ps">
      <Column Name="ps_id" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="person_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="skills_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="skills_ps" Member="skills" ThisKey="skills_id" OtherKey="skill_id" Type="skills" IsForeignKey="true" />
      <Association Name="employees_ps" Member="employees" ThisKey="person_id" OtherKey="employee_id" Type="employees" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.skills" Member="skills">
    <Type Name="skills">
      <Column Name="skill_id" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="skill_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="skills_ps" Member="ps" ThisKey="skill_id" OtherKey="skills_id" Type="ps" />
    </Type>
  </Table>
</Database>